### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by b4dnewz** [srsgores/generator-wordpress-plugin#7]
I see the package is not maintained and I would like to have mine published but there is a name conflict (_on npm_), can you consider the deprecation of this one in favor of one that is actively mainteined? @srsgores 

The package is this: [codekraft-studio/generator-wordpress-plugin](https://github.com/codekraft-studio/generator-wordpress-plugin)

Many thanks in advance, by the way good tool.

**Comment by b4dnewz** [comment]
any news on this?

**Comment by srsgores** [comment]
I did note your fork, and I think some of the changes would be welcome.  However, I did note some major differences:

1. Use of single quote and odd spacing in templates (no tabs)
2. Irregular usage of WordPress API
3. Gratuitous comments

I would welcome a pull request to **this** repository if you want to help maintain these templates.  Until then, users can downgrade their version of `yo`.

**Comment by b4dnewz** [comment]
@srsgores thanks for have seen the project. 
actually is not a fork and has more features.

I would like to argue a few things:

> Use of single quote and odd spacing in templates (no tabs)

I don't know where this come from but eslint (and most of javascript linters) defaults to single quotes, so I will need to add custom rule for that.

> Irregular usage of WordPress API

Most of the code is took from wordpress codex.

> Gratuitous comments

I like to make everybody understand what is going on in the code, probably is too verbose but it better than nothing.

After that, I'm disappointed that you still want to keep this repository active even if is not maintained, also most of the users of this repository complain about they can't install and use it ( #6, #5, #3 ).

No worry for the PR I will just change the name of my repository. 

Have a good day and I hope you will take some time to fix this repository.

**Comment by srsgores** [comment]
I appreciate your feedback and input.  I have not reviewed the latest changes to your repository, but I welcome any pull requests, provided they follow the same coding standards of this repository.  I have not had the opportunity to maintain this repository, so any contributions are welcome.

Thanks for understanding, and I look forward to your contributions.
